version: '3.8'

services:
  app:
    image: oanajim/consumer
    ports:
      - 8083:8083
    depends_on:
      - db
      - rabbitmq
    environment:
      spring.datasource.url: jdbc:mysql://db:3306/monitoring
      spring.datasource.username: root
      spring.datasource.password: oanasql23
  db:
    image: mysql:8
    environment:
      DATABASE_PORT: 3306
      MYSQL_ROOT_PASSWORD: oanasql23
      MYSQL_DATABASE: monitoring
#
#  producer:
#    image: oanajim/producer
#    ports:
#      - '8080:8080'
#    depends_on:
#      - rabbitmq

  rabbitmq:
    image: rabbitmq:3.12.9-management
    ports:
      - "5672:5672"
      - "15672:15672"
